### PR TITLE
Update README to reference a current example

### PR DESCRIPTION
**Pull request by MattDavies**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Maybe keep a simple example, then link to the more complex one?

**Comment by MattDavies** [comment]
Thoughts on that?

**Comment by JakeGinnivan** [comment]
Why `typeof(Application).Assembly.CodeBase.Replace("file:///", "")` rather than `typeof(Application).Assembly.Location` out of interest?

**Comment by MattDavies** [comment]
None in particular, grabbed from an existing project. Swapped out.

**Comment by JakeGinnivan** [comment]
Sweet, thanks!

**Pull request merged**
