### PR TITLE
Only output public attributes

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Should I add nested public as well?

**Comment by danielmarbach** [comment]
@JakeGinnivan ping

**Comment by terrajobst** [comment]
Looks solid to me, but I'm just an interested guest :-)

**Comment by danielmarbach** [comment]
Me as well. Exposed to the mercy of Jake ;) I'm sure his finger is already hovering over the merge button... :p

**Comment by danielmarbach** [comment]
@JakeGinnivan feel free to add me to the contributor list and send me the details. I'll make sure to take care of the other PRs and hopefully get the build working again.

**Pull request merged**
