### PR TITLE
use App_Packages convention

### LINKED ISSUE #10: Move the approval code to the App_Packages directory
As per point 2 here http://nikcodes.com/2013/10/23/packaging-source-code-with-nuget/

should also adopt the `{package-id}.{package-version}` since this helps with updates

this also allows people to exclude your nuget source package from stylecop and resharper inspections

Want a PR?

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #10

i also removed ExampleApiApprovalTest from the package. i think doco is a better place for that and it will break for anyone not using xunit

### CODE REVIEW

**Comment by SimonCropp** [comment]
note the version is now hard coded in a diff single location.

**Comment by SimonCropp** [comment]
also your website is case sensitive and doesnt do redirects

**Comment by SimonCropp** [comment]
@JakeGinnivan bump :)

**Comment by JakeGinnivan** [comment]
Been on a cruise ship so had no internet. Will probably sort when we get to Miami, otherwise early next week when back in London.

Sent from my Windows Phone
________________________________

**Comment by SimonCropp** [comment]
LOL. no worries. have fun

**Pull request merged**
